-- Useage example:
-- To get the damageMultiplier of the current difficulty: HORDE.Difficulty[HORDE.CurrentDifficulty].damageMultiplier

HORDE.Difficulty = {
    [1] = {
        name = "CASUAL", -- Easy difficulty, no Elites, more enemies.
        damageMultiplier = 1.4,
        enemyCountMultiplier = 1.4,
        rewardMultiplier = 0.4,
        healthMultiplier = 1.5,
        startMoneyMultiplier = 1.1,
        spawnRadiusMultiplier = 0.5,
        maxEnemiesAliveScaleFactor = 5,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 4,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.25,
        frostbiteSlow = 0.5,
        eliteHealthScaleAdd = 0.2,
        eliteHealthScaleMultiplier = 1.2,
        eliteMutationProbability = 0.4,
        mutationProbability = 0.25,
        additionalPack = 6,
        additionalAmmoBoxes = 12,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 1.5,
        xpMultiEnd = 3,
    },
    [2] = {
        name = "NORMAL", -- Normal difficulty.
        damageMultiplier = 1.8,
        enemyCountMultiplier = 1,
        rewardMultiplier = 0.4,
        healthMultiplier = 1.75,
        startMoneyMultiplier = 1.1,
        spawnRadiusMultiplier = 0.5,
        maxEnemiesAliveScaleFactor = 1.5,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 4,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.25,
        frostbiteSlow = 0.5,
        eliteHealthScaleAdd = 0.2,
        eliteHealthScaleMultiplier = 1.2,
        eliteMutationProbability = 0.4,
        mutationProbability = 0.5,
        additionalPack = 6,
        additionalAmmoBoxes = 12,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 3,
        xpMultiEnd = 5,
    },
    [3] = {
        name = "MEDIUM", -- Medium difficulty, more enemies.
        damageMultiplier = 1.8,
        enemyCountMultiplier = 1.4,
        rewardMultiplier = 0.3,
        healthMultiplier = 1.8,
        startMoneyMultiplier = 1.1,
        spawnRadiusMultiplier = 0.5,
        maxEnemiesAliveScaleFactor = 5,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 4,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.3,
        frostbiteSlow = 0.5,
        eliteHealthScaleAdd = 0.2,
        eliteHealthScaleMultiplier = 1.2,
        eliteMutationProbability = 0.4,
        mutationProbability = 0.6,
        additionalPack = 4,
        additionalAmmoBoxes = 2,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 3,
        xpMultiEnd = 5,
    },
    [4] = {
        name = "ELITE-RUSH", -- Medium-hard difficulty, Elites only.
        damageMultiplier = 1.8,
        enemyCountMultiplier = 1,
        rewardMultiplier = 0.3,
        healthMultiplier = 2,
        startMoneyMultiplier = 0.75,
        spawnRadiusMultiplier = 0.4,
        maxEnemiesAliveScaleFactor = 1.5,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 4,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.3,
        frostbiteSlow = 0.5,
        eliteHealthScaleAdd = 0.2,
        eliteHealthScaleMultiplier = 1.2,
        eliteMutationProbability = 0.4,
        mutationProbability = 1,
        additionalPack = 4,
        additionalAmmoBoxes = 2,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 3.5,
        xpMultiEnd = 5,
    },
    [5] = {
        name = "HARD", -- Hard difficulty, 100% mutation for non-Elite.
        damageMultiplier = 2,
        enemyCountMultiplier = 1.2,
        rewardMultiplier = 0.3,
        healthMultiplier = 2.2,
        startMoneyMultiplier = 0.75,
        spawnRadiusMultiplier = 0.4,
        maxEnemiesAliveScaleFactor = 2,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 5,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.5,
        frostbiteSlow = 0.75,
        eliteHealthScaleAdd = 0.3,
        eliteHealthScaleMultiplier = 1.4,
        eliteMutationProbability = 0.75,
        mutationProbability = 1,
        additionalPack = 4,
        additionalAmmoBoxes = 2,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 4,
        xpMultiEnd = 7,
    },
    [6] = {
        name = "VETERAN", -- Veteran difficulty, 100% mutation, extra enemies.
        damageMultiplier = 2.2,
        enemyCountMultiplier = 1.4,
        rewardMultiplier = 0.3,
        healthMultiplier = 2.4,
        startMoneyMultiplier = 0.75,
        spawnRadiusMultiplier = 0.4,
        maxEnemiesAliveScaleFactor = 3.5,
        poisonHeadcrabDamage = 75,
        statusDurationBonus = 5,
        breakHealthLeft = 0.25,
        shockDamageIncrease = 0.75,
        frostbiteSlow = 0.8,
        eliteHealthScaleAdd = 0.4,
        eliteHealthScaleMultiplier = 1.5,
        eliteMutationProbability = 1,
        mutationProbability = 1,
        additionalPack = 4,
        additionalAmmoBoxes = 2,
        hemorrhagePercentage = 0.5,
        xpMultiStart = 5.5,
        xpMultiEnd = 9,
    },
}

-- Making sure that all all keys are present
local requiredKeys = {
    "name",
    "damageMultiplier",
    "enemyCountMultiplier",
    "rewardMultiplier",
    "healthMultiplier",
    "startMoneyMultiplier",
    "spawnRadiusMultiplier",
    "maxEnemiesAliveScaleFactor",
    "poisonHeadcrabDamage",
    "statusDurationBonus",
    "breakHealthLeft",
    "shockDamageIncrease",
    "frostbiteSlow",
    "eliteHealthScaleAdd",
    "eliteHealthScaleMultiplier",
    "eliteMutationProbability",
    "mutationProbability",
    "additionalPack",
    "additionalAmmoBoxes",
    "hemorrhagePercentage",
}

for _, difficulty in pairs( HORDE.Difficulty ) do
    for _, key in pairs( requiredKeys ) do
        if difficulty[key] == nil then
            print( "Difficulty " .. difficulty.name .. " is missing key " .. key )
            ErrorNoHalt( "Difficulty " .. difficulty.name .. " is missing key " .. key .. "\n" )
        end
    end
end